### ISSUE TITLE
showTimesOnWeekView problem

### ISSUE THREAD

**Issue by IdoiaArroyo** [mattlewis92/angular-bootstrap-calendar#541] opened 2017-02-17 08:07 UTC
Hi, I have a little problem... When I use calendarConfig.showTimesOnWeekView = 'true', I can't use view day normally. When I select a range in any day, calendar creates an event on Monday of that week because calendar is always dated on Monday of that week...

Besides, I want to show events in week view but I've seen that this view shows initial date events but it doesn't  show final date of event so events look like that all are of 15 minutes.

Best regards.

Angular: 1.5.5
Calendar library: 0.28
Browser name and version: Chrome 46

**Comment by mattlewis92** [comment] 2017-02-19 18:24
I think this is a duplicate of: https://github.com/mattlewis92/angular-bootstrap-calendar/issues/536

As for the end times being ignored, this is a known caveat of using that feature (hence why it's not default). For some apps that don't use event end dates it's useful, otherwise I'd recommend sticking to the default view / building your own week view component and using it in conjunction with the day / month views with this lib.

**Closed by mattlewis92** 2017-02-19 18:24 UTC

**Comment by patricksmms** [comment] 2017-03-12 20:16
This is an important feature indeed. You really should consider adding it. The week view is very likely the most used, and commonly showing times.

**Comment by mattlewis92** [comment] 2017-03-12 20:18
@patricksmms I don't have the capacity to do this myself, but if someone sent a high quality PR with it, i'd be happy to review and merge it. Everyone here has the source code and are developers 😄

**Comment by patricksmms** [comment] 2017-03-12 20:21
@mattlewis92: Fair enough! I'll try to do it myself. Just came across your lib today, as I need a calendar for an angularjs app and there's nothing close to decent and free :P

**Comment by mattlewis92** [comment] 2017-03-12 20:24
That would be awesome, LMK if you need any guidance 😄

**Comment by burtek** [comment] 2017-03-12 21:01
I've been actually working on this for the last few days and was going to send PR this week, as soon as I make sure it works flawlessly.

**Comment by patricksmms** [comment] 2017-03-12 21:51
Can one of you just point me to where the height of the event is coming from, on the day view? Thanks

**Comment by mattlewis92** [comment] 2017-03-12 22:25
Off the top of my head I think it comes from a default CSS rule, you'll need to override it in the template with ng-style (like how the top, width etc are done)

**Comment by patricksmms** [comment] 2017-03-13 19:55
That part I figured out quickly, I'm asking about where the height of the even, on the **day** view is coming from. I wanted to use the same method for both, if possible.

**Comment by burtek** [comment] 2017-03-13 20:05
Look at lines 51-56 in [angular-bootstrap-calendar/src/templates/calendarDayView.html](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/templates/calendarDayView.html). The controller and directive responsible for this view are in [angular-bootstrap-calendar/src/directives/mwlCalendarDay.js](https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/directives/mwlCalendarDay.js)

**Comment by mattlewis92** [comment] 2017-03-13 20:07
Ah, it comes from the getDayViewFunction in the calendar utils lib: https://github.com/mattlewis92/calendar-utils/blob/master/src/calendarUtils.ts#L367

Which you can access here:
https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/services/calendarHelper.js#L294

**Comment by patricksmms** [comment] 2017-03-13 21:57
Apologies, I realised that I actually need a simpler user interface to display events, so I'll write my own custom. Good luck with this!

**Comment by mattlewis92** [comment] 2017-03-13 21:59
No worries! 😀
