### ISSUE TITLE
Is it possible to show only work day for the week view?

### ISSUE THREAD

**Issue by rz131s** [mattlewis92/angular-bootstrap-calendar#296] opened 2016-02-25 19:33 UTC
Hello,

I want to show only work day of the week for an addition week view. I can add the button for no problem, but seems the model doesn't support it. Is there any way that I can only show work day in the week without weekend?

Thanks!!

**Comment by swapy** [comment] 2016-02-26 04:17
This seems duplicate of #272

**Comment by mattlewis92** [comment] 2016-02-27 10:02
There isn't a way to do this as the architecture of the calendar is tied too closely to 7 days. You have a couple of options, you can either use the existing `cal-day-weekend` class on the day headers to style them to a disabled color or you could use a [custom template](https://github.com/mattlewis92/angular-bootstrap-calendar#configuring-the-calendar-default-config) for the week view and remove the days manually.

**Closed by mattlewis92** 2016-02-27 10:02 UTC

**Comment by stvnmntjy** [comment] 2016-07-14 22:26
Can this be done with a *custom, non-standard view*? Suppose you wanted to support both the full 7-day week view (which comes standard) and also a 5-day work week view (non-standard).

So, you don't want to *override* the standard week view template. You want to add a **new view**.

Let's say you call that view state: `"workweek"` and you set that on a button press (e.g. `vm.calendarView = 'workweek'` -- doesn't matter how it's set).

How do you tell the library "here's the custom template for `workweek`?"

Can I do this in `configProvider`? Can I do this with `custom-template-urls`? Will you show an example of both, if so?

I see something like setting a custom template in a test: https://git.io/vK0Vd but library usage examples would go a long way.

If you **can't** achieve this design with the library, how would you suggest toggling in-and-out the standard week template to support both work week and full week?

**Comment by mattlewis92** [comment] 2016-07-15 09:48
A custom template might work, you can see an e2e example of how to do that here: https://mattlewis92.github.io/angular-bootstrap-calendar/#?example=custom-templates

I would actually have 2 separate instances of the calendar, one with the custom template and one without, toggling between them should be pretty easy then. 

You'll probably need some extra business logic inside the template, for that I'd recommend creating a child component and inserting it into the custom template. Have the inputs as all the scope items like `vm.view` etc, and then manipulate them to remove the week days etc. You'll probably also need some custom styling as well to make the columns 20% width as well.

Alternatively for a really easy fix, just use the existing `cal-day-weekend` class that is applied to weekend days to make weekends appear disabled like so:
<img width="1025" alt="screen shot 2016-07-15 at 10 43 04" src="https://cloud.githubusercontent.com/assets/6425649/16870464/97c96524-4a79-11e6-9a59-dc5a7d6bd49c.png">
