### ISSUE TITLE
Drag & drop doesn't behave well in day view

### ISSUE THREAD

**Issue by pkeuter** [mattlewis92/angular-bootstrap-calendar#117] opened 2015-07-17 06:52 UTC
When I try to resize or drag an event in week-view. Weird things will happen.

For example: I have an event at 8.00AM. When I resize it at the bottom, the first time, it doesn't do anything. The second time it works well.

When I resize from the bottom, but drag it so the endtime and starttime are the same, the event won't be visible (this could be expected behavior, although I would say that it should ignore that)

When I drag the event down and release the mouse, the event gets moved 2 hours after the dropped-at time. For example: when I drag the event to 11AM, it gets moved to 1PM, although the time of the event is still the right time.

When I drag the event up and release the mouse, the same thing happens as when dragging down, but the event gets placed an hour before the dropped at time.

When I resize from the top, the resizing goes well. But when I release the mouse button, the event moves an half hour up (start time of the event is still alright). For example: The event starts at 8.00, I drag the top so it starts at 7.30, then the time will be 7.30 in the event, but the box will be at 7.00. Then when I start dragging it again, it jumps back to the right time, and when I release it, it jumps back.

I'm using your code for the on-event-times-changed
```
on-event-times-changed="calendarEvent.startsAt = calendarNewEventStart; calendarEvent.endsAt = calendarNewEventEnd"
```

Hope you can tell me what's wrong here. Because this doesn't work too well :-)

**Comment by mattlewis92** [comment] 2015-07-17 07:36
I can't reproduce anything in this, please could you provide me with an example plunker etc which reproduces your problem. Also what browser are you using?

**Comment by pkeuter** [comment] 2015-07-17 08:43
Using the latest Chrome. The weird thing is that I am unable to reproduce this using Plunkr, but it's still happening on my own site. Maybe there's another library interfering or something. Are there any libaries known to disturb the working of your calendar?

Thanks!

**Comment by mattlewis92** [comment] 2015-07-17 08:49
Not that I know of. Are you using any of the `day-view-start` `day-view-end` or `day-view-split` options? Also what version of the calendar are you using? Can you try 0.13.0 and see if that fixes it?

**Comment by pkeuter** [comment] 2015-07-17 08:52
I'm using neither of them. And I'm already on 0.13.0. I really don't know how to debug this either.

**Comment by mattlewis92** [comment] 2015-07-17 08:59
I'm not really sure, the only thing I could suggest is try debugging the source of the calendar directly and see if you can work out what's going wrong there.

**Comment by pkeuter** [comment] 2015-07-17 09:14
When I try this plunker. Everything works correctly: http://plnkr.co/edit/ynRm1e5YYmhJYE4Scw0c?p=preview

But when you move the calendar entry up and down, you see it jumping way out of scope. This is exactly the problem I'm having, with the difference that mine doesn't jump back to the right position whereas the plunker does.

**Comment by mattlewis92** [comment] 2015-07-17 09:19
What are you passing to `on-event-times-changed` ?

**Comment by pkeuter** [comment] 2015-07-17 09:20
``` on-event-times-changed="calendarEvent.startsAt = calendarNewEventStart; calendarEvent.endsAt = calendarNewEventEnd"
 ```

**Comment by pkeuter** [comment] 2015-07-17 09:24
By the way, it doesn't matter if I remove that code. The jumping still occurs.

**Comment by mattlewis92** [comment] 2015-07-17 18:10
Can you try now with 0.14.1

**Comment by pkeuter** [comment] 2015-07-18 09:48
Unfortunately, this doesn't solve it :-( Still the same problem. The items even can even get next to the headers (or above, but then you can't see them anymore). It appears that the further I drag, the further the item places itself.

The update does add another problem. The calendar doesn't load at first (only the headers load), but when I click next day or previous day, the grid shows up.

**Comment by mattlewis92** [comment] 2015-07-20 08:04
Are you using any custom CSS to modify the size of the grid / day view events? As the code makes assumptions that events on the day view are a fixed size. The easiest thing for you to do would just be to edit the source of the calendar and put a few console.logs in to see what's going on and you should quickly be able to spot the problem. This would be a good place to start: https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/directives/mwlDraggable.js#L107

As for the calendar not initially loading, I'm guessing it's because you're using a custom template url, and the child directives of the calendar won't be instantiated until the templates have been loaded. You can get around this by pre-loading your templates into the $templateCache

**Comment by pkeuter** [comment] 2015-07-24 07:57
I do use some custom css. But even after removing all of it, and all 'unneccesary' js, this problem exists. Very strange. I'll try to do some logging and see what's happening.

Calendar problem is solved with using the templatecache indeed. Thanks.

**Comment by pkeuter** [comment] 2015-07-24 12:02
Well, I guess someone already found the problem:
https://github.com/mattlewis92/angular-bootstrap-calendar/issues/121

I tried to disable jquery and the problem disappeared.

**Comment by mattlewis92** [comment] 2015-07-28 10:16
I don't use jquery in any of my projects (the whole reason I wrote this calendar was for this exact reason) so I never would have spotted this. I will release a new version shortly with the merged PR :)

**Closed by mattlewis92** 2015-07-28 10:16 UTC
Labels: needs more info
