### ISSUE TITLE
Demo in the source of 0.10.0 is not working properly

### ISSUE THREAD

**Issue by rossbg** [mattlewis92/angular-bootstrap-calendar#69] opened 2015-05-04 09:05 UTC
Hey,

when I download the zip of the source code and compile the less file, then the demo is not working properly.

The month view of the calendar is not actually opened, you need to start clicking between the week, day, etc views to get the calendar shown.

It was like that even before the release, while looking at the top of the master branch.

Downloading and testing the demo in the code of 0.9.2 works fine.

**Comment by mattlewis92** [comment] 2015-05-04 20:28
The demo is running [0.10.0](http://mattlewis92.github.io/angular-bootstrap-calendar/) fine. Please can you upload your code that reproduces the bug you are experiencing to a [plunkr](http://plnkr.co/) or something similar. Thanks.

**Comment by rossbg** [comment] 2015-05-05 06:31
Hey, thanks for the reply. Figured out the problem:
In the index.html the following prevents the calendar from initial display:

```
<style type="text/css">
      [ng-cloak] {
        display: none;
      }
</style>
```

**Comment by rossbg** [comment] 2015-05-05 07:27
Hey,

Thanks for the answer.

I am talking about the index.html in the source code.

It does not load as described above when using all the default multiple js includes:

```<script src="src/app.js"></script>

    <script src="src/directives/mwlCalendar.js"></script>

    <script src="src/filters/calendarTruncateEventTitle.js"></script>

    <script src="src/filters/calendarLimitTo.js"></script>

    <script src="src/services/calendarConfig.js"></script>

    <script src="src/services/calendarTitle.js"></script>

    <script src="src/services/calendarHelper.js"></script>

    <script src="src/services/calendarDebounce.js"></script>

    <script src="src/services/moment.js"></script>

    <script src="src/directives/mwlCollapseFallback.js"></script>

    <script src="src/directives/mwlDateModifier.js"></script>

    <script src="src/directives/mwlCalendarYear.js"></script>

    <script src="src/directives/mwlCalendarMonth.js"></script>

    <script src="src/directives/mwlCalendarWeek.js"></script>

    <script src="src/directives/mwlCalendarDay.js"></script>

    <script src="src/directives/mwlCalendarSlideBox.js"></script>```

It only works when using the provided builded file, which is not what I'm looking for:

`<script src="dist/js/angular-bootstrap-calendar-tpls.js"></script>`

Thanks for your time.

**Comment by mattlewis92** [comment] 2015-05-05 08:26
Using the source files is only really meant for development purposes, I don't quite get what your use case it for directly using the source files. At a guess I'd say it's because your directive template paths are wrong, does src/templates exist in your path? Without a plunker that reproduces your problem there isn't much I can do to help.

**Comment by anthonyvialleton** [comment] 2015-05-06 12:20
Hello, this [plunker](http://embed.plnkr.co/QcfaIAoenhppErN8F9oW/preview) shows the non closing item (working fine in 0.9.2).

PS : I made the few changes of event mapping to match the new version

**Comment by mattlewis92** [comment] 2015-05-06 13:32
@anthonyvialleton I've created a [new issue](https://github.com/mattlewis92/angular-bootstrap-calendar/issues/71) for your problem. By default the calendar will auto open the current date. You can stop this behaviour by setting auto-open="false" on the calendar.

**Comment by anthonyvialleton** [comment] 2015-05-06 13:39
Perfect! And what for your Demo and the plunker ?

**Comment by mattlewis92** [comment] 2015-05-06 13:39
It will be fixed in 0.10.1

**Comment by rossbg** [comment] 2015-05-06 16:48
My issue is reproducing when referencing the templates by filename, rather than being in the template cache. Exactly what is happening in the index.html in the source.

**Comment by mattlewis92** [comment] 2015-05-07 07:41
Does the src/templates path actually exist and point to the directive templates? A plunker would really be helpful to show me what you mean otherwise I'm just guessing.

**Comment by mattlewis92** [comment] 2015-05-18 18:42
Closing as this has gone stale. If you can provide a plunker then I'll happily assist in helping you otherwise there's not much I can do and no one else is getting this problem.

**Closed by mattlewis92** 2015-05-18 18:42 UTC
