### ISSUE TITLE
Directives unit test.

### ISSUE THREAD

**Issue by wawyed** [mattlewis92/angular-bootstrap-calendar#105] opened 2015-07-06 10:40 UTC
I've noticed you don't have any unit tests for your directives, is there any reason for that?

**Comment by mattlewis92** [comment] 2015-07-06 10:46
Mainly due to lack of time / motivation. I've tried to abstract as much logic from the directives into the services as possible, but it would be nice to have a complete test suite one day.

**Comment by wawyed** [comment] 2015-07-06 10:50
I need to build an event calendar on my project and I was thinking on integrating your calendar in our codebase, but we have a 95% code coverage policy so I might need to write unit test for all your directives before I can consider porting it over.

**Comment by mattlewis92** [comment] 2015-07-06 11:46
I'd happily accept a PR with the additional unit tests :) I'll add the project to coveralls to see what the coverage is currently like.

**Comment by wawyed** [comment] 2015-07-06 14:35
Do I need to change anything to run the build on windows? I seem to be getting issues with path names using / instead of \

**Comment by mattlewis92** [comment] 2015-07-06 14:45
I don't have any experience running node on windows I'm afraid. Changing this the forward slashes to backslashes on these lines: https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/webpack.config.js#L16 and https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/webpack.config.js#L10 might do the trick

**Comment by mattlewis92** [comment] 2015-07-06 18:50
I had some time this evening to try it on a VM, the issue is just with the npm script. Just run it directly by doing `npm install -g webpack-dev-server` then run `webpack-dev-server`

**Comment by mattlewis92** [comment] 2015-07-06 19:15
I've added coverage reporting for you as well: https://github.com/mattlewis92/angular-bootstrap-calendar/commit/a0c6c37c072aab1bb993b9d9b9a18e199fc66fe8

**Comment by wawyed** [comment] 2015-07-07 10:50
Thanks for that! although it doesn't seem to be ignored node_modules folder correctly...

**Comment by mattlewis92** [comment] 2015-07-07 10:55
Sorry I don't quite get what you mean

**Comment by wawyed** [comment] 2015-07-07 11:00
Have a look at my commit. https://github.com/wawyed/angular-bootstrap-calendar/commit/908386964ced94af6ef79fa8bce194083c182105. The way you wrote the RegExp didn't seem to work.

**Comment by mattlewis92** [comment] 2015-07-07 11:04
Ah, that would be another windows bug, it's to do with the trailing slash in the regex.

**Comment by wawyed** [comment] 2015-07-07 11:06
Also I managed to fix the issue with npm scripts by simply prefixing the command with node since you can't run files in windows. https://github.com/wawyed/angular-bootstrap-calendar/commit/0f9cbfd5c74f5370a70a9b262835b7ad40131d34

**Comment by mattlewis92** [comment] 2015-07-08 17:46
Thanks, I've added both those fixes into master :)Thanks, I've added both those fixes into master :)

**Comment by wawyed** [comment] 2015-07-09 09:25
I've noticed to tend to deregister watches on your directives scope when the scope is about to get destroyed. This is unnecessary since $destroy will stop any $digest to propagate to the destroyed scope (or it's children) hence the watch functions won't be called again. https://docs.angularjs.org/api/ng/type/$rootScope.Scope#$destroy

**Comment by mattlewis92** [comment] 2015-07-09 09:48
Just had a google and you're correct, the unbind isn't required for watchers and only for event listeners outside of angulars ecosystem. There are a lot of blog posts that have got this wrong though (plus the eslint plugin that I use!) e.g.
https://www.airpair.com/angularjs/posts/angularjs-performance-large-applications

**Comment by wawyed** [comment] 2015-07-09 09:54
That's weird and unfortunate.

Aditionally, when you do this:

    unbindOnDestroy.push($scope.$watch('currentDay', refreshCalendar));
    unbindOnDestroy.push($scope.$watch('view', refreshCalendar));
    unbindOnDestroy.push($scope.$watch('events', refreshCalendar, true));

You have to create a debounce function with a random delay (50) to avoid refreshing 3 times, is it not possible to use $watchGroup to achieve the same thing without having to debounce?

    unbindOnDestroy.push($scope.$watchGroup(['currentDay', 'view', 'events'], refreshCalendar));

**Comment by mattlewis92** [comment] 2015-07-09 09:59
The random delay was because the templates were being loaded asynchronously on dev, they're now built into the package so that isn't needed any more. As for $watchGroup the calendar currently supports ng 1.2, and $watchGroup is only available 1.3+, but once I drop 1.2 support I can remove all of that:
https://github.com/mattlewis92/angular-bootstrap-calendar/issues/58

**Comment by wawyed** [comment] 2015-07-09 10:59
I committed the first two unit tests, https://github.com/wawyed/angular-bootstrap-calendar/commit/6b3a2020dc57f40489c3db7d0be487526dae6ff0.

**Comment by mattlewis92** [comment] 2015-07-09 14:29
Great stuff, thanks! If you make a PR when you're done I'll merge it in :)

**Comment by wawyed** [comment] 2015-07-10 10:56
How so you only update the list of hours for the day only if the locale changes? (mwlCalendarHours.js line 29)

What if I want to change day-view-start or day-view-end?

**Comment by mattlewis92** [comment] 2015-07-10 11:01
Good spot, that's a bug.

**Comment by wawyed** [comment] 2015-07-10 11:25
mwlCalendarSlideBox.js line 13. Why do you need this watch? You already have isOpen in the scope as a bind between your isolate scope and the parent. All you need to do is use !isOpen in your template instead of defining a new variable 'shouldCollapse'. Unless I am missing something.

**Comment by mattlewis92** [comment] 2015-07-10 11:32
IIRC it's a workaround to prevent a flicker with the ui-bootstrap collapse directive. It might be possible to remove it though.

**Comment by wawyed** [comment] 2015-07-10 16:08
mwlDraggable.js line 70 Were you meant $parse it? or just read the attribute value, because looking at the usage it seems that it always returns undefined.

**Comment by mattlewis92** [comment] 2015-07-11 10:52
I definitely meant to parse it, and it works in the demo as the week and day views are locked to the correct axis:
https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/templates/calendarWeekView.html#L48

**Comment by wawyed** [comment] 2015-07-11 10:55
Maybe it's just this file then https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/templates/calendarDayView.html ?

**Comment by mattlewis92** [comment] 2015-07-11 15:46
I've integrated all your feedback into master now, the unit tests are looking great so far!

**Comment by wawyed** [comment] 2015-07-13 09:20
mwlCalendar.js line 52. It appears to be that this line will never get called since angular.copy creates a new object reference $scope.view === previousView will never true. Were you meant to use angular.equals?

Also, did you have a look at mwlCalendarHourList.js line 29 as I mentioned in my previous comment (though you might have missed it)?

**Comment by mattlewis92** [comment] 2015-07-13 09:24
$scope.view is a string not an object so comparing them via === will work. The angular.copy on line 35 isn't needed.

r.e. the hour list see: https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/directives/mwlCalendarHourList.js#L36

**Comment by wawyed** [comment] 2015-07-13 09:33
You are right it is a string, I think the angular.copy threw me off.

Hour list: I missed that change :). Do you need https://github.com/mattlewis92/angular-bootstrap-calendar/blob/master/src/directives/mwlCalendarHourList.js#L44 taking into a account that a watch always fires the first time (even if the values haven't changed) 

According to https://docs.angularjs.org/api/ng/type/$rootScope.Scope. 

>After a watcher is registered with the scope, the listener fn is called asynchronously (via $evalAsync) to initialize the watcher. In rare cases, this is undesirable because the listener is called when the result of watchExpression didn't change. To detect this scenario within the listener fn, you can compare the newVal and oldVal. If these two values are identical (===) then the listener was called due to initialization.

**Comment by mattlewis92** [comment] 2015-07-13 09:35
Nope, it's not needed, I guess I forgot to remove that line.

**Comment by wawyed** [comment] 2015-07-14 08:36
I was having a look at calendarDate and I've noticed that it's a stateful filter, although according to angular docs that it's not recommended. Is there a reason for doing it this way? https://docs.angularjs.org/guide/filter#stateful-filters

>It is strongly discouraged to write filters that are stateful, because the execution of those can't be optimized by Angular, which often leads to performance issues. Many stateful filters can be converted into stateless filters just by exposing the hidden state as a model and turning it into an argument for the filter.

>If you however do need to write a stateful filter, you have to mark the filter as $stateful, which means that it will be executed one or more times during the each $digest cycle.

**Comment by mattlewis92** [comment] 2015-07-14 08:41
It's stateful because the locale can change. Passing the current locale in as a parameter to the filter would remove the need for it though.

**Comment by mattlewis92** [comment] 2015-07-14 19:35
Closing this now as everything has been dealt with. Will close the last few issues within the next few days and release 0.14 that include your tests :)

**Closed by mattlewis92** 2015-07-14 19:35 UTC
Labels: enhancement
