### ISSUE TITLE
The list of event not working when i'm setting a timezone by default using moment.

### ISSUE THREAD

**Issue by CLenon** [mattlewis92/angular-bootstrap-calendar#472] opened 2016-10-21 22:15 UTC
When I set a default timezone to the calendar, in the month view the list of events from a timespan selected it is not displaying.

### Versions

Angular: ^1.5.8

Calendar library: ^0.24.0

Browser name and version: Chrome 53.0.2785.143

**Comment by mattlewis92** [comment] 2016-10-22 16:36
Please provide a plunker that reproduces your problem (you can create a starter template by hitting the plunker button on the demo page). Thanks!

**Comment by mattlewis92** [comment] 2016-10-26 16:06
Closing due to lack of reproduction.

**Closed by mattlewis92** 2016-10-26 16:06 UTC

**Comment by CLenon** [comment] 2016-10-26 17:52
Thanks, for your answer. I already solved the issue i had.
